#dev -> main PR 시, 태그 적용
name: Auto Versioning & Tagging

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get_tag
        run: |
          # 최신 태그가 있으면 가져오고, 없으면 "v0.0.0"을 기본값으로 설정
          TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Bump Version
        id: bump_version
        run: |
          OLD_TAG=${{ env.LATEST_TAG }}
          # 기존 태그가 "v"로 시작한다고 가정하고, 버전을 증가
          VERSION=$(echo $OLD_TAG | sed 's/v//' | awk -F. '{print $1"."$2"."$3+1}')
          NEW_TAG="v$VERSION"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
